# Generated by Django 4.2 on 2023-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_concert_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='song',
            field=models.ManyToManyField(related_name='concerts', to='music.song', verbose_name='Songs'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Concert Title'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Part Name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Song Title'),
        ),
    ]
