# Generated by Django 4.2 on 2023-04-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_concert_song_alter_concert_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='season',
            field=models.IntegerField(choices=[(1, 'Fall'), (2, 'Christmas'), (3, 'February'), (4, 'Spring')], default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.file'),
        ),
        migrations.AlterField(
            model_name='song',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.part'),
        ),
    ]
