# Generated by Django 4.2 on 2023-04-23 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_concert_season_alter_file_pdf_alter_part_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='song',
        ),
        migrations.RemoveField(
            model_name='part',
            name='file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='part',
        ),
        migrations.AddField(
            model_name='file',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.part'),
        ),
        migrations.AddField(
            model_name='part',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='concert',
            field=models.ManyToManyField(blank=True, null=True, related_name='concerts', to='music.concert'),
        ),
    ]
