# Generated by Django 4.2 on 2023-04-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_concert_song_remove_part_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='concert',
            field=models.ManyToManyField(null=True, related_name='concerts', to='music.concert'),
        ),
    ]
