# Generated by Django 4.2 on 2023-04-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_song_concert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='concert',
            field=models.ManyToManyField(blank=True, to='music.concert'),
        ),
    ]
