# Generated by Django 4.2 on 2023-04-26 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0009_alter_song_concert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="file",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="music.part",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="music.song",
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="concert",
            field=models.ManyToManyField(blank=True, related_name="songs", to="music.concert"),
        ),
    ]
