# Generated by Django 4.2 on 2023-05-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0010_alter_file_options_alter_file_part_alter_part_song_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={},
        ),
        migrations.AlterModelOptions(
            name="part",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="file",
            name="page_num",
        ),
        migrations.RemoveField(
            model_name="file",
            name="title",
        ),
        migrations.RemoveField(
            model_name="part",
            name="song",
        ),
        migrations.AddField(
            model_name="file",
            name="file_name",
            field=models.CharField(default="null-init", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="song",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="music.song"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="songs",
            field=models.ManyToManyField(blank=True, related_name="parts", to="music.song"),
        ),
        migrations.AlterField(
            model_name="file",
            name="part",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="music.part"
            ),
        ),
    ]
