# Generated by Django 4.2 on 2023-04-19 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('season', models.IntegerField(choices=[(1, 'Fall'), (2, 'Christmas'), (3, 'February'), (4, 'Spring')])),
                ('performance_date', models.DateTimeField(verbose_name='Performance Date')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('concert', models.ManyToManyField(related_name='songs', to='music.concert')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_dt', models.DateTimeField(verbose_name='Created Date')),
                ('modified_dt', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.part')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
    ]
