# Generated by Django 4.2 on 2023-04-19 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='performance_date',
        ),
        migrations.RemoveField(
            model_name='file',
            name='part',
        ),
        migrations.RemoveField(
            model_name='file',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='concert',
        ),
        migrations.AddField(
            model_name='concert',
            name='song',
            field=models.ManyToManyField(null=True, related_name='concerts', to='music.song'),
        ),
        migrations.AddField(
            model_name='file',
            name='page_num',
            field=models.IntegerField(default=1, verbose_name='Page Number'),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='part',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.file'),
        ),
        migrations.AddField(
            model_name='song',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='music.part'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateTimeField(verbose_name='Performance Date')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.concert')),
            ],
        ),
    ]
