# Generated by Django 4.2 on 2023-04-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_concert_performance_date_remove_file_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='song',
            field=models.ManyToManyField(related_name='concerts', to='music.song'),
        ),
    ]
